# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snake_sim/protobuf/remote_snake.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'snake_sim/protobuf/remote_snake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%snake_sim/protobuf/remote_snake.proto\x12\tsnake_sim\"\x1d\n\x05\x43oord\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x15\n\x07SnakeId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1d\n\x0bSnakeLength\x12\x0e\n\x06length\x18\x01 \x01(\x05\"9\n\rStartPosition\x12(\n\x0estart_position\x18\x01 \x01(\x0b\x32\x10.snake_sim.Coord\"\x17\n\x07\x45nvData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"5\n\x0eUpdateResponse\x12#\n\tdirection\x18\x01 \x01(\x0b\x32\x10.snake_sim.Coord\"\x07\n\x05\x45mpty2\x8d\x03\n\x0bRemoteSnake\x12-\n\x05GetId\x12\x10.snake_sim.Empty\x1a\x12.snake_sim.SnakeId\x12-\n\x05SetId\x12\x12.snake_sim.SnakeId\x1a\x10.snake_sim.Empty\x12\x37\n\tGetLength\x12\x12.snake_sim.SnakeId\x1a\x16.snake_sim.SnakeLength\x12\x35\n\tSetLength\x12\x16.snake_sim.SnakeLength\x1a\x10.snake_sim.Empty\x12>\n\x10SetStartPosition\x12\x18.snake_sim.StartPosition\x1a\x10.snake_sim.Empty\x12\x33\n\x0bSetInitData\x12\x12.snake_sim.EnvData\x1a\x10.snake_sim.Empty\x12;\n\x06Update\x12\x12.snake_sim.EnvData\x1a\x19.snake_sim.UpdateResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snake_sim.protobuf.remote_snake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORD']._serialized_start=52
  _globals['_COORD']._serialized_end=81
  _globals['_SNAKEID']._serialized_start=83
  _globals['_SNAKEID']._serialized_end=104
  _globals['_SNAKELENGTH']._serialized_start=106
  _globals['_SNAKELENGTH']._serialized_end=135
  _globals['_STARTPOSITION']._serialized_start=137
  _globals['_STARTPOSITION']._serialized_end=194
  _globals['_ENVDATA']._serialized_start=196
  _globals['_ENVDATA']._serialized_end=219
  _globals['_UPDATERESPONSE']._serialized_start=221
  _globals['_UPDATERESPONSE']._serialized_end=274
  _globals['_EMPTY']._serialized_start=276
  _globals['_EMPTY']._serialized_end=283
  _globals['_REMOTESNAKE']._serialized_start=286
  _globals['_REMOTESNAKE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
