# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snake_sim/protobuf/remote_snake.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'snake_sim/protobuf/remote_snake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%snake_sim/protobuf/remote_snake.proto\x12\x0cremote_snake\"\x07\n\x05\x45mpty\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"5\n\x0bSnakeAction\x12&\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x16.remote_snake.Position\"@\n\x07\x45nvData\x12\x0f\n\x03map\x18\x01 \x03(\x05\x42\x02\x10\x01\x12$\n\x04\x66ood\x18\x02 \x03(\x0b\x32\x16.remote_snake.Position\"\x91\x01\n\x0bInitEnvData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\tFOOD_TILE\x18\x03 \x01(\x05\x12\x11\n\tFREE_TILE\x18\x04 \x01(\x05\x12\x14\n\x0c\x42LOCKED_TILE\x18\x05 \x01(\x05\x12\'\n\x08\x65nv_data\x18\x06 \x01(\x0b\x32\x15.remote_snake.EnvData2\x92\x01\n\x12RemoteSnakeService\x12@\n\x0esetInitEnvData\x12\x19.remote_snake.InitEnvData\x1a\x13.remote_snake.Empty\x12:\n\x06update\x12\x15.remote_snake.EnvData\x1a\x19.remote_snake.SnakeActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snake_sim.protobuf.remote_snake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVDATA'].fields_by_name['map']._loaded_options = None
  _globals['_ENVDATA'].fields_by_name['map']._serialized_options = b'\020\001'
  _globals['_EMPTY']._serialized_start=55
  _globals['_EMPTY']._serialized_end=62
  _globals['_POSITION']._serialized_start=64
  _globals['_POSITION']._serialized_end=96
  _globals['_SNAKEACTION']._serialized_start=98
  _globals['_SNAKEACTION']._serialized_end=151
  _globals['_ENVDATA']._serialized_start=153
  _globals['_ENVDATA']._serialized_end=217
  _globals['_INITENVDATA']._serialized_start=220
  _globals['_INITENVDATA']._serialized_end=365
  _globals['_REMOTESNAKESERVICE']._serialized_start=368
  _globals['_REMOTESNAKESERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
