# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from snake_sim.protobuf import sim_msgs_pb2 as snake__sim_dot_protobuf_dot_sim__msgs__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in snake_sim/protobuf/sim_msgs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteSnakeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.initEnvData = channel.unary_unary(
                '/snakesim.RemoteSnakeService/initEnvData',
                request_serializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.Empty.SerializeToString,
                response_deserializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.EnvData.FromString,
                _registered_method=True)
        self.update = channel.stream_stream(
                '/snakesim.RemoteSnakeService/update',
                request_serializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.SnakeAction.SerializeToString,
                response_deserializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.EnvData.FromString,
                _registered_method=True)


class RemoteSnakeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def initEnvData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteSnakeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'initEnvData': grpc.unary_unary_rpc_method_handler(
                    servicer.initEnvData,
                    request_deserializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.Empty.FromString,
                    response_serializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.EnvData.SerializeToString,
            ),
            'update': grpc.stream_stream_rpc_method_handler(
                    servicer.update,
                    request_deserializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.SnakeAction.FromString,
                    response_serializer=snake__sim_dot_protobuf_dot_sim__msgs__pb2.EnvData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snakesim.RemoteSnakeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snakesim.RemoteSnakeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteSnakeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def initEnvData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snakesim.RemoteSnakeService/initEnvData',
            snake__sim_dot_protobuf_dot_sim__msgs__pb2.Empty.SerializeToString,
            snake__sim_dot_protobuf_dot_sim__msgs__pb2.EnvData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/snakesim.RemoteSnakeService/update',
            snake__sim_dot_protobuf_dot_sim__msgs__pb2.SnakeAction.SerializeToString,
            snake__sim_dot_protobuf_dot_sim__msgs__pb2.EnvData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
